#pragma once

#include "costumer.h"

Costumer costumers[10] = { Costumer("João da Silva Santos",
                                    "Rua A",
                                    "Centro",
                                    "Cidade A",
                                    "123.456.789-00",
                                    "0"),
                           Costumer("Maria de Oliveira Souza",
                                    "Avenida B",
                                    "Bairro X",
                                    "Cidade B",
                                    "987.654.321-00",
                                    "1"),
                           Costumer("Pedro Alves Pereira",
                                    "Rua C",
                                    "Bairro Y",
                                    "Cidade C",
                                    "111.222.333-00",
                                    "2"),
                           Costumer("Ana dos Santos Pereira",
                                    "Avenida D",
                                    "Bairro Z",
                                    "Cidade D",
                                    "444.555.666-00",
                                    "3"),
                           Costumer("Carlos Oliveira Silva",
                                    "Rua E",
                                    "Bairro W",
                                    "Cidade E",
                                    "777.888.999-00",
                                    "4"),
                           Costumer("Lúcia Almeida Souza Pereira",
                                    "Avenida F",
                                    "Bairro V",
                                    "Cidade F",
                                    "888.777.666-00",
                                    "5"),
                           Costumer("Fernando da Silva Almeida",
                                    "Rua G",
                                    "Bairro U",
                                    "Cidade G",
                                    "555.444.333-00",
                                    "6"),
                           Costumer("Mariana Alves dos Santos",
                                    "Avenida H",
                                    "Bairro T",
                                    "Cidade H",
                                    "222.333.444-00",
                                    "7"),
                           Costumer("Rafael Pereira Oliveira",
                                    "Rua I",
                                    "Bairro S",
                                    "Cidade I",
                                    "999.888.777-00",
                                    "8"),
                           Costumer("Beatriz Santos Almeida",
                                    "Avenida J",
                                    "Bairro R",
                                    "Cidade J",
                                    "666.777.888-00",
                                    "9") };

std::string products[10] = { "Camiseta Branca",
                             "Calça Jeans Azul",
                             "Sapato de Couro Marrom",
                             "Celular Smartphone Android",
                             "Fone de Ouvido Bluetooth",
                             "Mochila Escolar Preta",
                             "Relógio de Pulso Analógico",
                             "Cadeira de Escritório Giratória",
                             "Notebook Ultrafino Prateado",
                             "Máquina de Café Automática" };
